### ISSUE TITLE
uploadSkin method returns TypeError

### ISSUE THREAD

**Issue by KennethNero** [Jack92829/Mojang-API-Wrapper#6]
When trying to upload a skin in the same directory as the running program the process does not complete and returns `TypeError: Object of type BufferedReader is not JSON serializable`.

The code snippit that reproduces this error is below:

```
from MojangAPI import Client
import asyncio

skin_file = "skin.png"
username = "username"
email = "email"
password = "password"


async def upload_skin():
    user = await Client.User.createUser(username)
    await user.authenticate(email, password)
    await user.uploadSkin(skin_file)


loop = asyncio.get_event_loop()
loop.run_until_complete(upload_skin())
```

So far it doesn't look like a path issue, but may be the fact that an open file (BuffedReader in this case?) is being passed on line 193 of Client.py.

**Comment by Jack92829** [comment]
Hey could you send the full error so I can have a look at the traceback

**Comment by KennethNero** [comment]
Sure thing!
[log.txt](https://github.com/Jack92829/Mojang-API-Wrapper/files/5432082/log.txt)

**Comment by Jack92829** [comment]
I believe it's all fixed now, I uploaded the fixed version to pypi so you can just run `pip install --upgrade MojangAPI`

**Comment by Jack92829** [comment]
Let me know if it's all good

**Comment by KennethNero** [comment]
Works perfectly, thanks for the quick fix!
